### ISSUE TITLE
Which IPEX version is supported as the backend

### ISSUE THREAD

**Issue by leslie-fang-intel** [facebookresearch/torchdynamo#112]
I think the latest IPEX has no method of `_optimize_catch_errors` , may I kindly know which IPEX version is supported as the default `ipex` optimization backend? https://github.com/facebookresearch/torchdynamo/blob/476ca6b7c148dd6705bf218684dfe05c6cd9fcfb/torchdynamo/optimizations/backends.py#L281-L285

**Comment by leslie-fang-intel** [comment]
cc @jiayisunx @jgong5

**Comment by jansel** [comment]
The latest commit at the time of my testing was:
```
commit 7e679d05c938358d78988407d1458c9d9af8b9ff
Author: jiayisunx <jiayi.sun@intel.com>
Date:   Fri Oct 29 12:42:23 2021 +0800

    remove AdaptiveMaxPool2d and AvgPool2d from blacklist (#270)
    
    * remove AdaptiveMaxPool2d and AvgPool2d from blacklist
    
    * set upsample as FallThrough in autocast
    
    Co-authored-by: Wang Weihan <eikan.wang@intel.com>
```

I haven't tested this backend since then, so it is possible things have changed upstream since then.

PRs to fix this are welcome!

**Comment by leslie-fang-intel** [comment]
Thanks for the quick comment @jansel. From the code snip below
https://github.com/facebookresearch/torchdynamo/blob/476ca6b7c148dd6705bf218684dfe05c6cd9fcfb/torchdynamo/optimizations/backends.py#L281-L285
I think `_optimize_catch_errors` should be a method of `ipex`, but I don't think ipex provides this kind of method (even with the commit you provide: 7e679d05c938358d78988407d1458c9d9af8b9ff).
Does `torchdynamo` have done some magic thing to provide this method of ipex?

**Comment by leslie-fang-intel** [comment]
Thanks for the confirm @jansel.
