### ISSUE TITLE
[Question] Why we need to run the model several times inside optimizer

### ISSUE THREAD

**Issue by leslie-fang-intel** [facebookresearch/torchdynamo#129]
Refer to this code:
```
from typing import List
import torch
import torchdynamo

def toy_example(a, b):
    x = a / (torch.abs(a) + 1)
    if b.sum() < 0:
        b = b * -1
    return x * b

def my_compiler(gm: torch.fx.GraphModule, example_inputs: List[torch.Tensor]):
    print("my_compiler() called with FX graph:")
    gm.graph.print_tabular()
    return gm.forward  # return a python callable

with torchdynamo.optimize(my_compiler):
    for _ in range(1 or 2):
        toy_example(torch.randn(10), torch.randn(10))
```
Inside the `torchdynamo.optimize`, if I run 1 time or 2 times, it generates different sub-graph. Why we need to run the model several times inside torchdynamo.optimize?

**Comment by leslie-fang-intel** [comment]
When I run this example, sometimes it prints 2 graph and sometimes it print 3 graph.

**Comment by jansel** [comment]
You don't need to run the model several times, that was mean't to demonstrate the 3 graphs.  In most cases running once is enough.

The 3 graphs come from the `if b.sum() < 0:`
1) One graph for everything before the `if` (followed by a graph break)
2) A second graph if you take the `true` branch of the `if`
3) A third graph if you take the `false` branch of the `if`


You are seeing either 2 or 3 graphs based on the randomness on if `b.sum()` is positive or negative.

**Comment by leslie-fang-intel** [comment]
Thanks for the feedback. So if I write this kind of code, here is some of understanding:
In the `torchdynamo.optimize`, we only run the model once(we keep the formal running in the `torchdynamo.run`). That's meaning only one path of the `if` condition will be hit and optimized for this sub-graph. The remained path of the `if` condition will not be compiled and optimized.
Is there any way to ensure all the sub-graph is compiled before we enter into `torchdynamo.run`?

```
from typing import List
import torch
import torchdynamo

def toy_example(a, b):
    x = a / (torch.abs(a) + 1)
    if b.sum() < 0:
        b = b * -1
    return x * b

def my_compiler(gm: torch.fx.GraphModule, example_inputs: List[torch.Tensor]):
    print("my_compiler() called with FX graph:")
    gm.graph.print_tabular()
    return gm.forward  # return a python callable

with torchdynamo.optimize(my_compiler):
    toy_example(torch.randn(10), torch.randn(10))

with torchdynamo.run():
    toy_example(torch.randn(10), torch.randn(10))
```

**Comment by jansel** [comment]
That is correct.

In general there is no guarantee of 100% coverage.  This is true even if you don't have control flow.  For example, TorchDynamo specializes on dtype/device/etc, so if you call toy_example() with a tensor on a different device/dtype it will recompile.

**Comment by leslie-fang-intel** [comment]
Thanks for the comment. The recompile will happens in context of `torchdynamo.optimize` but not `torchdynamo.run`, right?
How about I put every model running inside context of `torchdynamo.optimize`? in case there are some recompiled needed.
For this way, will it have some performance impact comparing with `torchdynamo.run`?

**Comment by jansel** [comment]
Yes, if you hit a novel device/type/control-flow/etc:
1) inside `torchdynamo.optimize` it compiles a new graph
2) inside `torchdynamo.run` it falls back to eager mode

The performance of `optimize` and `run` should be identical in the case of a cache-hit, and only differ in what they do on a cache-miss.
