### ISSUE TITLE
Side effect to OrderedDict doesn't allow resumption

### ISSUE THREAD

**Issue by ezyang** [facebookresearch/torchdynamo#131]
```
from typing import List
import torch
import torchdynamo
import collections

torchdynamo.config.debug = True

def toy_example(a, b, d):
    x = a + b
    d[3] = 1
    return x * b

d = collections.OrderedDict()
with torchdynamo.optimize("eager"):
    for i in range(4):
        toy_example(torch.randn(10), torch.randn(10), d)
print(d)
```

prints

```
MODIFIED BYTECODE
  8           0 LOAD_GLOBAL              0 (__compiled_fn_0)
              2 LOAD_FAST                0 (a)
              4 LOAD_FAST                1 (b)
              6 CALL_FUNCTION            2
              8 UNPACK_SEQUENCE          1
             10 STORE_FAST               3 (x)

 10          12 LOAD_CONST               1 (1)
             14 LOAD_FAST                2 (d)
             16 LOAD_CONST               2 (3)
             18 STORE_SUBSCR

 11          20 LOAD_FAST                3 (x)
             22 LOAD_FAST                1 (b)
             24 BINARY_MULTIPLY
             26 RETURN_VALUE
```

I expected there to be generated continuation function so torchdynamo could capture x * b.

**Comment by jansel** [comment]
Should be somewhat easy to add support for this as [regular dict mutation](https://github.com/facebookresearch/torchdynamo/blob/main/torchdynamo/side_effects.py#L273) is already supported (without a graph break) and [all dicts are ordered in Python 3.7+](https://medium.com/junior-dev/python-dictionaries-are-ordered-now-but-how-and-why-5d5a40ee327f).  So just a matter of making OrderedDict go down the same codepath as dict.

**Comment by ezyang** [comment]
There is also a more general question I have, which is that many opcodes don't have `break_graph_if_unsupported`. In principle, wouldn't it be sound to break graph for all unsupported opcodes, assuming that everything on the stack can be restored?

**Comment by jansel** [comment]
You could get there to be a continuation by:
1) Adding a [break_graph_if_unsupported](https://github.com/facebookresearch/torchdynamo/blob/f2efb835a5092e817b5ab12b8a62ae8fd3fc7e90/torchdynamo/symbolic_convert.py#L135) decorator to [STORE_SUBSCR](https://github.com/facebookresearch/torchdynamo/blob/f2efb835a5092e817b5ab12b8a62ae8fd3fc7e90/torchdynamo/symbolic_convert.py#L638)
2) Changing the 1 to a 0 on [this line](https://github.com/facebookresearch/torchdynamo/blob/f2efb835a5092e817b5ab12b8a62ae8fd3fc7e90/torchdynamo/symbolic_convert.py#L149).  `STORE_SUBSCR` pushes 0 items unto the stack, while currently `break_graph_if_unsupported` assumes 1.  We should move this to an arg.
3) Comment out [this line](https://github.com/facebookresearch/torchdynamo/blob/f2efb835a5092e817b5ab12b8a62ae8fd3fc7e90/torchdynamo/symbolic_convert.py#L151).  Same issue as above, `break_graph_if_unsupported` assumes 1 thing is pushed, which needs to get passed to the continuation function.

In principle adding `break_graph_if_unsupported` to way more places would be sound provided you got the stack_effect right.  It already checks that everything on the stack can be restored.

**Comment by jansel** [comment]
I will add that one limit of the current `resume_at_x` code is it only partially supports exception handlers.  I think that is fixable though.

**Comment by jansel** [comment]
I'll add that one challenge (that is only partially solved right now) of `resume_at_X` continuations is exception handlers.  This gets mapped to the concept of a "block" in python bytecode.  I think this is solvable, but would require more work.

This example doesn't use try/except though -- so not an issue here.
