### ISSUE TITLE
Handle torch.seed - AssertionError: torch.* op returned non-Tensor

### ISSUE THREAD

**Issue by anijain2305** [facebookresearch/torchdynamo#136]
Repro

~~~
import sys
import torch
import torchdynamo

def fn():
    # randomize seeds
    # use cuda generator if available
    if (
        hasattr(torch.cuda, "default_generators")
        and len(torch.cuda.default_generators) > 0
    ):
        # GPU
        device_idx = torch.cuda.current_device()
        attention_seed = torch.cuda.default_generators[device_idx].seed()
    else:
        # CPU
        attention_seed = int(torch.seed() % sys.maxsize)

    torch.manual_seed(attention_seed)


fn()

with torchdynamo.optimize(lambda gm: gm.forward):
    fn()
~~~

**Comment by jansel** [comment]
We might be able to map the result of `seed()` to a DynamicShapeVariable:
https://github.com/facebookresearch/torchdynamo/blob/f2efb835a5092e817b5ab12b8a62ae8fd3fc7e90/torchdynamo/variables/tensor.py#L271

Or possibly introduce a new (very similar) TensorVariable subclass for it.

**Comment by anijain2305** [comment]
Trying to understand. Why can't seed be a ConstantVariable, instead of a TensorVariable? Is it because the value is supposed to change for each iteration?

The expression here is 

~~~
attention_seed = int(torch.seed() % sys.maxsize)
~~~

This requires us to support `mod` on a TensorVariable and then `int` on a TensorVariable.

**Comment by anijain2305** [comment]
Ah, I see. It cannot be a ConstantVariable, because then we will lose the connection between the def and use of `attention_seed` in the above example. We need to track the dependencies.

**Comment by anijain2305** [comment]
Fixed by https://github.com/facebookresearch/torchdynamo/pull/141
