### ISSUE TITLE
[Question] How does torchdynamo hook the python bytecode and generate FX Graph?

### ISSUE THREAD

**Issue by leslie-fang-intel** [facebookresearch/torchdynamo#137]
From the code inside `torchdynamo/torchdynamo/symbolic_convert.py`：

- Looks like torchdynamo hooks the python bytecode(such as `CALL_FUNCTION`, `LOAD_FAST`) to generate the FX Graph, is my understand right? 
- Could we have some details about what's information torchdynamo get from the hook functions and how to generate the FX Graph from these information? 

Thanks.

**Comment by leslie-fang-intel** [comment]
Thanks for the comment.

- The hook functions in my understanding are these methods of `InstructionTranslatorBase`: [LOAD_FAST](https://github.com/facebookresearch/torchdynamo/blob/main/torchdynamo/symbolic_convert.py#L304), [CALL_FUNCTION](https://github.com/facebookresearch/torchdynamo/blob/main/torchdynamo/symbolic_convert.py#L540) .etc.  

- I think that's where we get the information to generate the FX Graph. But I am not understanding the details:
  - how to  symbolically evaluate the bytecode?
  - how to generate the FX Graph from the information we get (I suppose it's getting from the evaluating bytecode symbolically)?

**Comment by jansel** [comment]
`InstructionTranslator` converts bytecode to an FX Graph (plus modified bytecode).

Those methods (like LOAD_FAST), are called from this line:
https://github.com/facebookresearch/torchdynamo/blob/a460bde3e6bc14d4872230982ae8755e6ff54400/torchdynamo/symbolic_convert.py#L252

Given a `LOAD_FAST` bytecode instruction with an `inst.opname == "LOAD_FAST"`, that line will call the [LOAD_FAST method](https://github.com/facebookresearch/torchdynamo/blob/a460bde3e6bc14d4872230982ae8755e6ff54400/torchdynamo/symbolic_convert.py#L304).

**Comment by leslie-fang-intel** [comment]
Thanks @jansel. That's same as my understanding.
Can you explain more about how `InstructionTranslator` converts bytecode to an FX Graph (plus modified bytecode)?

**Comment by ezyang** [comment]
@leslie-fang-intel I'm planning to do a deep dive streaming session. Maybe you can attend or watch the recording when I'm done :)

**Comment by leslie-fang-intel** [comment]
Thanks @ezyang. That's great. Looking forward for the sharings.

**Comment by ezyang** [comment]
3PM EST tomorrow, save the date

**Comment by ezyang** [comment]
stream at https://www.youtube.com/watch?v=egZB5Uxki0I&t=1s
