### ISSUE TITLE
[Question]How dose TorchDynamo provide larger average speedups than the other backends shown

### ISSUE THREAD

**Issue by jiayisunx** [facebookresearch/torchdynamo#148]
The data you provide in [TorchDynamo Update 3: GPU Inference Edition](https://dev-discuss.pytorch.org/t/torchdynamo-update-3-gpu-inference-edition/460) shows that TorchDynamo provides a 1.71x geometric mean speedup on CPU. May I ask How does this speedup work?  Does TorchDynamo generate multiple subgraphs to get more opportunities to improve performance, or does the backend itself used by TorchDynamo provide higher performance?

**Comment by jansel** [comment]
It uses the same approach as [described in the updated before that](https://dev-discuss.pytorch.org/t/torchdynamo-update-1-48x-geomean-speedup-on-torchbench-cpu-inference/397).  It has an autotuner to select the best backend for each graph.  The graph boundaries are whatever TorchDynamo happened to find at the time, there is no graph splitting.

**Comment by jiayisunx** [comment]
Thanks for your answer, from the table, we can see that most models have a large speedup by using TorchDynamo, but timm_efficientnet only has 0.66x performance, do you know why?

**Comment by jiayisunx** [comment]
@jansel , thanks a lot.
