### ISSUE TITLE
Add support for Python 3.9

### ISSUE THREAD

**Issue by jansel** [facebookresearch/torchdynamo#33]
The process for adding support for Python 3.9 is as follows.

First, examine the [10 new bytecodes in 3.9](https://docs.python.org/3.9/library/dis.html):

RERAISE
raising exceptions is currently not supported and breaks the graph.  So this can just call `unimplemented()` for now.  See issue #35 for more on exceptions.

WITH_EXCEPT_START
might affect support for `with no_grad():` and related ops

LOAD_ASSERTION_ERROR
LIST_TO_TUPLE
LIST_EXTEND
SET_UPDATE
DICT_UPDATE
DICT_MERGE
IS_OP
CONTAINS_OP
these are all simple aliases for things TorchDynamo already supports and should be easy to handle

Next, update the versions supported in `setup.py` so the build works.

Next, iteratively add support for ops and fix issues until all tests pass.  `pytest tests` to run tests.

Next, iteratively fix issues in ./torchbench.py until all models pass and match the coverage of Python 3.8

**Comment by jansel** [comment]
Looks like 3.9 also added 
_PyInterpreterState_SetEvalFrameFunc https://docs.python.org/dev/c-api/init.html#c._PyInterpreterState_SetEvalFrameFunc
and added a new `PyThreadState *tstate` arg to the the eval_frame function:  
https://docs.python.org/dev/c-api/init.html#c._PyFrameEvalFunction

Both of those will require changes to _eval_frame.c

**Comment by jansel** [comment]
@hsrussell is taking a look at this one

**Comment by yanboliang** [comment]
Fixed by https://github.com/facebookresearch/torchdynamo/pull/154
