### ISSUE TITLE
Add support for Python 3.10

### ISSUE THREAD

**Issue by jansel** [facebookresearch/torchdynamo#34]
Python 3.9 (#33) should be added before 3.10.

Known issues for Python 3.10 support:

Python 3.10 and later have a new method for mapping the bytecode index to line number, deprecating co_lnotab.  See [PEP 626](https://peps.python.org/pep-0626/).  [lnotab_writer](https://github.com/facebookresearch/torchdynamo/blob/052b8dab6df5f027a34edb00dee73870433883d5/torchdynamo/bytecode_transformation.py#L58) in TorchDynamo needs to be rewritten to support the new format.   See #36 for more on line numbers.

There are [9 new/changed bytecodes in 3.10](https://docs.python.org/3.10/library/dis.html)

COPY_DICT_WITHOUT_KEYS
GET_LEN
MATCH_MAPPING
MATCH_SEQUENCE
MATCH_KEYS
MATCH_CLASS
Look like easy to add aliases for already supported things.

MAKE_FUNCTION
Handling of annotations changed.  We should add a test case to make sure annotations work for nested functions.

ROT_N
Seems easy to add.  We should update usage of [rot_n_helper](https://github.com/facebookresearch/torchdynamo/blob/052b8dab6df5f027a34edb00dee73870433883d5/torchdynamo/utils.py#L336) to use this new bytecode instead.

GEN_START
This could break handling of inline generators.  Need to look into this in more detail.

**Comment by yanboliang** [comment]
Fixed by https://github.com/facebookresearch/torchdynamo/pull/172, now TorchDynamo supports Python 3.10!
