### ISSUE TITLE
Issue with demucs model

### ISSUE THREAD

**Issue by frank-wei** [facebookresearch/torchdynamo#98]
The demucs model will throw at:

cuda eval  demucs                             Traceback (most recent call last):
  File "torchbench.py", line 957, in <module>
    main()
  File "torchbench.py", line 824, in main
    run_one_model(
  File "torchbench.py", line 904, in run_one_model
    assert not torchdynamo.utils.is_jit_model(submod)
AssertionError

Here is the command to repro: python torchbench.py -dcuda --speedup-fx2trt-fp16 --only demucs

**Comment by frank-wei** [comment]
It solves this problem. Thanks.

**Comment by jansel** [comment]
Lets keep this open until the fix lands.  I've been mostly working off of my [fork](github.com/jansel/benchmark) that has a bunch of fixes applied.
